### ISSUE TITLE
Avatar Search broken

### ISSUE THREAD

**Issue by Murkur** [pypy-vrc/VRCX#64]
Recent update to the API for avatars has now required authentication with the users authcookie and no longer only requires an APIKEY

**Comment by GotoFinal** [comment]
i cant get it to work at all for global list of avatars. it returns one avatar for me. and its one of my avatars.

**Comment by GenesisAria** [comment]
Also tested, manually applying my auth cookie on the url only calls back my own public avatars.

**Comment by pypy-vrc** [comment]
it was fixed by itself. 🤔

**Comment by Fusl** [comment]
API version `master-build-2020-07-10-arya-metahannah` had this "issue", developers however rolled this back to `master-build-2020-07-07-hand-chloroastrid`, so time will tell if this was intentional or a bug.

**Comment by ChillPenguinVR** [comment]
Is the avatar search not working still an issue? or am I just unlucky that it still doesnt work for me after re-installing vrcx?

**Comment by Murkur** [comment]
avatar search is still broken for some reason requesting avatar lists from users works fine tho

**Comment by ChillPenguinVR** [comment]
pretty sureI figured out why. vrchat did stuff to the public API key because every single client/mod uses the same api key. A normal user should only use at most 14 api requests an hour. When looking at the average api requests that the key was getting, It was over 6000 an hour acrossed all users (modded and unmodded).

**Comment by GenesisAria** [comment]
The behaviour seems to be back again.

**Comment by Blackout-tech** [comment]
Trying to search for a friends avatar, and it says "Avatar search is not possible" Is this a issue that has happened in the past?
![Screenshot_6](https://user-images.githubusercontent.com/68805214/90624423-c7ce8580-e1cc-11ea-8a89-253031507883.png)
![Screenshot_7](https://user-images.githubusercontent.com/68805214/90624491-e46abd80-e1cc-11ea-88d6-ef3006c0eec3.png)

**Comment by Murkur** [comment]
this is not broken avagar search is just not possible in vrchat
